### PR TITLE
Remove library jsonrpcclient from hm_pyhelper 

### PR DESCRIPTION
**Pull request by ilyastrodubtsev**
**How**
Remove jsonrpcclient library from source code. And start using 'requests' library for all requests.

**Checklist**

- [x] Tests fixed
- [x] Cleaned up commit history (rebase!)

### CODE REVIEW

**Comment by marvinmarnold** [comment]
@ilyastrodubtsev can you provide more context? Is there still some dependency clash? Is it a best practice to use requests library instead?

**Comment by ilyastrodubtsev** [comment]
@marvinmarnold We discussed this problem with @robputt.
It was originally due to dependency issues.
Now more specific. Due to frequent critical updates. As I understand it, this is not the first time we have rewritten this section of code, due to the fact that serious changes have taken place in the jsonrpсclient library.

Since the standard request functions are removed from the jsonrpсclient library now [docs link](https://composed.blog/jsonrpcclient-4-changes). And in connection with this, we need to use the requests library for requests.
It's easier to stop using jsonrpсclient library. And use the requests library.

**Review by marvinmarnold — APPROVED** [review]
Thanks for the clarification @ilyastrodubtsev

**Review by robputt — CHANGES_REQUESTED** [review]
Looks good, but can we refactor it so we avoid the generic exception code smell from SonarCloud?

**Review by robputt — APPROVED** [review]
Approve 👍

**Pull request merged**
