### PR TITLE
feat: bump protobuf to 4.21.12

### PR DESCRIPTION
**Pull request by shawaj**
**Issue**

- Link:
- Summary:

**How**

- update requirements.txt version
- regenerate protos with latest versions

**Screenshots**

**References**

**Checklist**

- [x] Tests added
- [x] Cleaned up commit history (rebase!)
- [x] Documentation added
- [x] Thought about variable and method names

### CODE REVIEW

**Comment by shawaj** [comment]
had to regenerate protos using protoc - however not sure I have done it correctly.

@NebraLtd/developers I don't suppose any of you have experience with protobuf / protoc? And would be able to check this

**Comment by pritamghanghas** [comment]
Not sure what was the reason for updating protobuff but I don't see any issues.

**Comment by shawaj** [comment]
No real reason @pritamghanghas other than for it to be on latest up to date versions

**Comment by shawaj** [comment]
will merge this without version update, and then update version in #208

**Pull request merged**
