### PR TITLE
fix: correct helium OG reset pin

### PR DESCRIPTION
**Pull request by shawaj**
**Issue**

- Link: N/A
- Summary: helium og miner has wrong reset pin

**How**

correct reset pin for helium OG

**Screenshots**

**References**

**Checklist**

- [x] Tests added
- [x] Cleaned up commit history (rebase!)
- [x] Documentation added
- [x] Thought about variable and method names

### CODE REVIEW

**Review by marvinmarnold — APPROVED** [review]
I wonder if we should be converting most flat values to dictionaries like we did with [STATUS_LED](https://github.com/NebraLtd/hm-pyhelper/blob/2abef166194cc1826f34e6555dd1dd433530e54d/hm_pyhelper/hardware_definitions.py#L367). This would mean keeping these changes for backward compatibility and also adding an entry like:

```
PRIMARY_BUTTON: {
  GPIO_NUMBER: 7
}
```

**Comment by shawaj** [comment]
@marvinmarnold do you mean in cases where, for example, there is more than one button or more than one LED?

**Comment by marvinmarnold** [comment]
Even if all hotspots had only one button/LED, the current naming is not clear (eg is that a pin or GPIO number?). Another reason is admittedly a premature optimization, but by using dicts, we are setting ourselves up to be able to have variant specific behavior (different wait times, feature flags only possible on some devices, etc). And yea, if some devices have multiple buttons, then labeling buttons like `PRIMARY_BUTTON` or `BUTTON1` is helpful.

**Comment by shawaj** [comment]
@marvinmarnold how about I merge this one, and move that suggestion to a new issue and the work to fix in into a new PR?

**Pull request merged**
