### PR TITLE
fix: update button pin IDs

### PR DESCRIPTION
**Pull request by shawaj**
**Issue**

- Link: https://github.com/NebraLtd/hm-config/issues/96
- Summary: support RockPi with button and led features

**How**

as we are moving to mraa in hm-config we will use physical pin definitions for button and status LEDs instead of the system pin numbers (as per https://wiki.radxa.com/Rockpi4/dev/libmraa )

**Screenshots**

N/A

**References**

Ref https://github.com/NebraLtd/hm-config/issues/96
Ref https://github.com/NebraLtd/hm-config/blob/2297842825bac09b9b0338681c2219b5338b1ea8/gatewayconfig/gatewayconfig_app.py#L90-L93

**Checklist**

- [x] Tests added
- [x] Cleaned up commit history (rebase!)
- [x] Documentation added
- [x] Thought about variable and method names

### CODE REVIEW

**Comment by shawaj** [comment]
Will bump version number before merge

**Comment by shawaj** [comment]
Not sure if this is what you had in mind @marvinmarnold or if there's a better way?

**Review by marvinmarnold — APPROVED** [review]
Yea this looks like it will work. I was thinking of adding additional fields just for this, but this works too.

**Comment by shawaj** [comment]
@marvinmarnold do you think it would be better to add additional ones for mraa? Will we need to use these in a non-mraa setting directly from the filesystem do you think?

**Comment by shawaj** [comment]
Maybe something like MRAA_LED and MRAA_BUTTON perhaps

**Comment by marvinmarnold** [comment]
> Maybe something like MRAA_LED and MRAA_BUTTON perhaps

I prefer verbose names. `GPIO_PIN_LED` and `GPIO_PIN_BUTTON`. Could also add `GPIO_NUM_LED` and `GPIO_NUM_BUTTON` and deprecate `STATUS` and `LED`. 

There isn't any need for the GPIO number values today. But there's no harm in having there in case.

**Comment by shawaj** [comment]
Changing STATUS and LED requires changing other stuff in different repos so maybe just leave those as is as GPIO numbers and for ROCK Pi add GPIO_PIN_LED and GPIO_PIN_BUTTON for now?

Can always change STATUS and LED further down the line as part of a more in depth refactor / update of names in here.

What do you think?

**Comment by shawaj** [comment]
ok have updated now to add those @marvinmarnold how does that look?

**Comment by marvinmarnold** [comment]
> ok have updated now to add those @marvinmarnold how does that look?

LGTM

**Pull request merged**
