### PR TITLE
Bugfix for get payload from clearsigned message

### PR DESCRIPTION
**Pull request by kashifpk**
`util.get_payload_from_clearsigned_message` was not extracting payload correctly if the original payload file used for signing did not end with a new line. This fixes it.

### CODE REVIEW

**Review by marvinmarnold — APPROVED** [review]
A regression test would be nice

**Comment by kashifpk** [comment]
> A regression test would be nice

Existing test actually covered it. A test should have been there for earlier implementation where it failed for payloads without a new line at the end. But since current logic covers both that test isn't needed now.

**Comment by marvinmarnold** [comment]
> A test should have been there for earlier implementation where it failed for payloads without a new line at the end. But since current logic covers both that test isn't needed now.

@kashifpk IMHO a test should be written for every bugfix. They are regression tests because they ensure the same bug never re-emerges. It sounds like the test you mention above would be exactly what we need. 

* Disclaimer: I haven't actually looked at the relevant test code

**Comment by kashifpk** [comment]
> > A test should have been there for earlier implementation where it failed for payloads without a new line at the end. But since current logic covers both that test isn't needed now.
> 
> @kashifpk IMHO a test should be written for every bugfix. They are regression tests because they ensure the same bug never re-emerges. It sounds like the test you mention above would be exactly what we need.
> 
>     * Disclaimer: I haven't actually looked at the relevant test code

That's a fair point. Addressed that in https://github.com/NebraLtd/hm-pyhelper/pull/138

**Pull request merged**
