### PR TITLE
Helper function to extract payload from PGP clearsigned message files.

### PR DESCRIPTION
**Pull request by kashifpk**
**Issue**

PGP helper code.

**Checklist**

- [X] Tests added
- [X] Cleaned up commit history (rebase!)
- [X] Documentation added
- [X] Thought about variable and method names

### CODE REVIEW

**Comment by ilyastrodubtsev** [comment]
Can might payload change a little?
For example. Also the most useful load.
But the lack of spaces between lines?

**Comment by kashifpk** [comment]
> Can might payload change a little? For example. Also the most useful load.

I didn't want to put structure of payload from our private repos in a public repo that's why the payload is like this.

> But the lack of spaces(empty lines) between lines?

Can you explain? These empty lines are generated by GPG and this is the actual format so can't really modify that.

**Comment by ilyastrodubtsev** [comment]
For example: In test case we have example of payload: 
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

{
  "key1": "value1",
  "key2": [1, 2, 3, 4]
}

-----BEGIN PGP SIGNATURE-----

some info there
-----END PGP SIGNATURE-----
```

I thought about the possibility of getting the payload in the format like: 
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512
{
  "key1": "value1",
  "key2": [1, 2, 3, 4]
}

-----BEGIN PGP SIGNATURE-----

some info there
-----END PGP SIGNATURE-----
```
But taking into account the fact that it is generated. I think my fears are unfounded.

**Comment by vpetersson** [comment]
@kashifpk should we not have this helper function being a bit more complete? At this point just does some minor text validation. Ideally I think we would want it such that you could just call on the function like `validate_gpg_payload(payload, public_key)`, where it either returns either the message if it matches, or an error.

**Comment by kashifpk** [comment]
> @kashifpk should we not have this helper function being a bit more complete? At this point just does some minor text validation. Ideally I think we would want it such that you could just call on the function like `validate_gpg_payload(payload, public_key)`, where it either returns either the message if it matches, or an error.

@vpetersson I thought about that but that meant adding the `python-gpg` library dependency to hm-pyhelper instead of that being in `hm-diag` since `hm-diag` is the only place where we actually do that validation.

I only placed this function in here because it would get used both by HPT and hm-diag. At HPT end we use it to extract the destination name from payload for display in the console and label printing. Since payload validation is specific to hm-diag and we already have a library for that (making it a single call), I thought it best to leave it out here.

**Pull request merged**
